name: Release

on:
  push:
    branches:
      - master

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  release:
    if: github.repository == 'nerdslabs/teiler'
    permissions:
      contents: write # to create release (changesets/action)
      pull-requests: write # to create pull request (changesets/action)
    needs: [tests]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          node-version: 24.x
          cache: pnpm
          registry-url: https://registry.npmjs.org
      - name: Install Dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v2
        with:
          version-script: pnpm changeset:version
          publish-script: pnpm changeset:publish
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
