name: Tests

on:
  workflow_call:
  pull_request:

jobs:
  jest:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Enable corepack
        run: corepack enable
      - uses: actions/cache@v4
        id: pnpm-cache
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ runner.os }}-${{ matrix.node-version }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-pnpm-
      - name: Install Dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm test -- --ci --coverage
  storybook:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
        package: [{ name: 'svelte', port: 6006 }, { name: 'vue', port: 6007 }]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Enable corepack
        run: corepack enable
      - uses: actions/cache@v4
        id: pnpm-cache
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ runner.os }}-${{ matrix.node-version }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-pnpm-
      - name: Install Dependencies
        run: |
          pnpm install
          pnpm playwright install --with-deps chromium
      - name: Build
        run: pnpm build
      - name: Run tests
        run: |
          cd packages/${{ matrix.package.name }}
          pnpm dlx concurrently -k -s first -n "STORYBOOK,TEST" -c "magenta,blue" \
            "pnpm storybook" \
            "pnpm dlx wait-on tcp:${{ matrix.package.port }} && pnpm test-storybook --url http://localhost:${{ matrix.package.port }}"
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Enable corepack
        run: corepack enable
      - uses: actions/cache@v4
        id: pnpm-cache
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install Dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm lint
  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Enable corepack
        run: corepack enable
      - uses: actions/cache@v4
        id: pnpm-cache
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install Dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm check-format
